### ISSUE TITLE
Server 1

### ISSUE THREAD

**Issue by JTan04** [Anderson-Lab/compare_web#7]
As an application, I would like to have a server to be hosted on node.js

**Comment by pauleanderson** [comment]
what's the ip address? can we access yet?

**Comment by JTan04** [comment]
Yes!
I set up the server on heroku and the url is https://damp-everglades-43957.herokuapp.com/
Currently it is deployed off of my computer since I do not have admin privileges for the GitHub repository, but we should be able to quickly set it up with your credentials.
